### ISSUE TITLE
Bot not opening media port on AKS correctly

### ISSUE THREAD

**Issue by jbrmg** [microsoftgraph/microsoft-graph-comms-samples#457]
**Describe the issue**
We are using the [AKS recording bot sample](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/AksSamples/teams-recording-bot). We managed to setup the sample successfully on our local development machines in combination with ngrok. However, we are having difficulties getting the sample to work on our AKS instance.

Whenever we instruct the bot to join a Teams meeting, the bot fails with a `MediaControllerConversationAddParticipantFailed` exception after the `CallEstablishing` event, which indicates that the Teams backend has issues accessing the media port on our bot. We do have setup the bot with the appropriate certificates for our domain and also setup the `AzureSettings_ServiceDnsName` configuration value accordingly. The bot does start without visible issues. 

It appears to us as if the media port was not opened successfully. When we curl the bot instances locally and in AKS, we see different outputs on the media port:

Bot running locally:
```
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Bot running on AKS:
```
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Expected behavior**
We expect the media port to be opened successful. 

**Graph SDK (please complete the following information):**
 - Microosft.Graph.Communications.Calls 1.2.0.850

**Call ID**
Call-ID: 80202e00-0d74-4541-9155-141dd4450c25 
Timestamp: 2021-06-01T11:37:44.178667700Z

**Logs**
Application startup logs:
```
Setup: Converting certificate
Setup: Installing certificate
Certificate "domain-anonymized.com" added to store.

CertUtil: -importPFX command completed successfully.
Setup: Deleting bindings
Setup: Adding bindings
Setup: Done
---------------------
RecordingBot: booting
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Created a new Aria trace listener with token 60d5a17c7f9d4fc3a788f76306c56932-17828cc4-fc68-4361-984a-9c6c88fee139-7032
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Setting MediaAgents platform log level to Information
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Setting MediaApiLogLevel to Warning
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Setting AvMP log level to Warning
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Attempting to apply the UnifiedLogging configuration: UnifiedLoggingConfiguration: [ IsEnabled: False ScenarioStrings:  []
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Setting UnifiedLogging Info: [isEnabled: False[] [ScenarioStrings: []
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Logger initialized for application ID <appId-anonymized>. Logging configuration: LoggingConfiguration: [ MediaAgentsPlatformLogLevel: Information; MediaApiLogLevel: Warning; MediaProcessorLogLevel: Warning; AriaLoggingConfiguration: AriaLoggingConfiguration: [ AriaTenantToken: 60d5a17c7f9d4fc3a788f76306c56932-17828cc4-fc68-4361-984a-9c6c88fee139-7032; AriaTraceEventName: SkypeMediaBotsTraces; SplitAriaTracesByLevel: True; DisableAriaTracing:  []; UnifiedLoggingConfiguration: UnifiedLoggingConfiguration: [ IsEnabled: False ScenarioStrings:  [] ]
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] New telemetry configuration: TelemetryConfiguration: [ AriaTenantToken: 60d5a17c7f9d4fc3a788f76306c56932-17828cc4-fc68-4361-984a-9c6c88fee139-7032 MonitorUnhandledExceptions: True MonitorSocketMetrics: True []
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Whitelist config value changed: cipnoam.api.mpaas.trafficmanager.net,intnoam.api.mpaas.trafficmanager.net,dognoam.api.mpaas.trafficmanager.net,prdnoam.api.mpaas.trafficmanager.net,prdapac.api.mpaas.trafficmanager.net,prdemea.api.mpaas.trafficmanager.net,prd00apac.mpaas.trafficmanager.net,prd00noam.mpaas.trafficmanager.net,prd00emea.mpaas.trafficmanager.net,mediapaas-api-test-01-wus.cloudapp.net,ucapnoam.api.mpaas.trafficmanager.net,mediapaas-api-apac.pub.ngcmtls.com,mediapaas-api-aus.pub.ngcmtls.com,mediapaas-api-dog.pub.ngcmtls.com,mediapaas-api-emea.pub.ngcmtls.com,mediapaas-api-int.pub.ngcmtls.com,mediapaas-api-noam.pub.ngcmtls.com,mediapaas-api-test.pub.ngcmtls.com,mediapaas-api-prod.gov.ngcmtls.us,mediapaas-api-prod.dod.ngcmtls.us,mediapaas-api.pub.ngcmtls.com,mediapaas-api-prd.pub.ngcmtls.com
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Minimum supported version config changed: 1.8.0.2
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Comparing bots version 1.19.0.0025 and minimum supported version 1.8.0.2
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] TelemetryWriter is not null, not creating a new one
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Platform has 4 cores
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Initializing MP with Service FQDN: domain-anonymized.com, Instance public port: 31672, Instance internal port: 8445
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] UseMPAzureAppHostPerfCounterProvider is false. Discarding MP perf counters
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] MediaPerf is not registered: no key found at SYSTEM\CurrentControlSet\Services\MediaPerf\Performance
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] UseMPAzureAppHostPerfCounterProvider is false. Not checking for perf counter registration
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] MP Service Event: ReportEvent_MPSVC_I_SERVICE_STARTING
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:47.591.00000002 (AVMP,InitializeHostMonitor:MediaProcessor.cs(1537)) [MP[] InitializeHostMonitor: Set supportunencryptedaudioportrange to false!
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:47.601.00000003 (AVMP,InitializeHostMonitor:MediaProcessor.cs(1537)) [MP[] InitializeHostMonitor: Set UseBundledPortRangeForConsumer to false!
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:47.601.00000004 (AVMP,InitializeHostMonitor:MediaProcessor.cs(1537)) [MP[] InitializeHostMonitor: Set UseBundledPortRangeForBusiness to false!
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:47.601.00000005 (AVMP,InitializeHostMonitor:MediaProcessor.cs(1553)) [MP[] InitializeHostMonitor: Set bundledminportrange to false!
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:47.601.00000006 (AVMP,InitializeHostMonitor:MediaProcessor.cs(1553)) [MP[] InitializeHostMonitor: Set bundledmaxportrange to false!
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.21::06/01/2021-11:53:47.613.00000007 (AVMP,WriteThreadHeartBeat:workitemqueue.cs(126)) [MP[] ThreadPool: Received invalid thread id 0
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.22::06/01/2021-11:53:47.616.00000008 (AVMP,WriteThreadHeartBeat:workitemqueue.cs(126)) [MP[] ThreadPool: Received invalid thread id 0
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.23::06/01/2021-11:53:47.621.00000009 (AVMP,WriteThreadHeartBeat:workitemqueue.cs(126)) [MP[] ThreadPool: Received invalid thread id 23
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.35::06/01/2021-11:53:47.629.0000000A (AVMP,WriteThreadHeartBeat:workitemqueue.cs(126)) [MP[] ThreadPool: Received invalid thread id 35
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.61::06/01/2021-11:53:47.635.0000000B (AVMP,WriteThreadHeartBeat:workitemqueue.cs(126)) [MP[] ThreadPool: Received invalid thread id 0
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.62::06/01/2021-11:53:47.635.0000000C (AVMP,WriteThreadHeartBeat:workitemqueue.cs(126)) [MP[] ThreadPool: Received invalid thread id 0
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:49.419.00000003 (MPSERVICEHOSTLIB,EndInitialize:MPHostImpl.cs(777)) [MPServiceHost[] EndInitialize - Blocking
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] MP Service Event: ReportEvent_MPSVC_I_SERVICE_STARTED
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Initialized MP With Uri: [net.tcp://domain-anonymized.com:31672/MediaProcessor]
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:49.533.0000000D (AVMP,OnPublicRtpIPAddressChanged:MediaProcessor.cs(724)) MediaProcessor.OnPublicRtpIPAddressChanged, Interpreting Public Address [0.0.0.0[] as 'not configured'
[AvMP[][AppId:<appId-anonymized>[] TL_WARN(TF_COMPONENT) [MEETING-BACKEND[]5660.1::06/01/2021-11:53:49.534.0000000E (AVMP,OnPublicRtpIPAddressChanged:MediaProcessor.cs(753)) MediaProcessor.OnPublicRtpIPAddressChanged, Configuring public Addresses failed due to invalid or missing mappings
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Set PIP on MP: [0.0.0.0[]
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] MP workload configuration set to [(500,500)]
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Initialized MediaApi Platform
[SkypeBotsMediaPlatform[][AppId:<appId-anonymized>[] Initialized MediaPlatform. ApplicationId : <appId-anonymized>, MPUri: net.tcp://domain-anonymized.com:31672/MediaProcessor, IsTest: False.
Assembly: GraphCommunicationsClient
Application: RecordingBot.Services
Product: GraphCommunicationsClient-RecordingBot.Services
Version: 1.2.0.850
UserAgent: GraphCommunicationsClient-RecordingBot.Services/1.2.0.850
Dispatcher Container registering notification dispatcher for: communications/calls
Subscribed: communications/calls
To queue: communications/calls
Listening on: https://+:9441/
Listening on: https://+:9441/0/
Listening on: http://+:9442/
RecordingBot: running
```

**Additional context**
We are using Traefik as gateway instead of NGINX and adjusted the ingress accordingly.

**Question**
How can we validate that the media port was opened correctly and exclude the ingress as possible origin of the issue?

**Comment by dongkyunn** [comment]
Your call failed since the backend server couldn't connect to "net.tcp://dev-platform.digitale-teams.de:31672/MediaProcessor"
Please make sure whether the following step was configured properly.

ClusterIP Service
One ClusterIP Service is deploy for each pod deployed using .Values.scale.maxReplicaCount. Each service points to a specific pod in the StatefulSet. This service is responsible for routing TCP traffic to the pod.

Each service exposes and maps .Values.internal.media to the pod in the StatefulSet.

ConfigMap
A ConfigMap is used to bind the external TCP port exposed by the external load balancer to a specific pod in the StatefulSet. To do this, when deploying Ingress-Nginx it is important to pass an argument to the container telling the bot where to find the ConfigMap. If you're deploying Ingress-Nginx using Helm, you can do this with --set controller.extraArgs."tcp-services-configmap"=teams-recording-bot/tcp-services.

When deploying, Helm iterates .Values.scale.maxReplicaCount number of times, and creates an entry for .Values.public.media + current iteration, mapping it to a specific ClusterIP Service and .Values.internal.media.

The end result is something like this:

28550: teams-recording-bot/teams-recording-bot-0:8445

**Comment by 1fabi0** [comment]
As addition also make sure your firewall is not blocking traffic like outgoing udp and tcp traffic or incoming tcp traffic to http port or media platform port

**Comment by jbrmg** [comment]
Hi @dongkyunn and @1fabi0 , 

thanks for your response.

Yes, we have made sure that each bot instance has its own Kubernetes service with a cluster IP assigned. We are using traefik instead of NGINX as gateway, but this shouldn't be an issue. Our service maps from port 8445 to port 8445 on the bot instance while Traefik forwards traffik from the external port 31672 to the service port 8445. Traefik also shows that is has found the service in Kubernetes and tries to forward the traffik to the ClusterIP of that service.

However, as stated in my original message, the bot instance always resets the connection as shown in the traefik logs:

`level=error msg="Error during connection: read tcp 10.240.0.34:37512->10.200.0.5:8445: read: connection reset by peer"`

As stated in the original message, the `connection reset by peer` can also be seen when I `curl http://localhost:8445` from within the bot's pod, so a firewall should not be an issue.

Last but not least, the `connection reset by peer` message cannot be observed when I run the bot locally with ngrok, which is why I conclude that the bot for some reason does not open its port correctly.

Do you have any more ideas on how to tackle the issue?


Thanks

**Comment by 1fabi0** [comment]
What do you have entered for your instance public port? It should be the port of traefik so 31672 and the Instance internal port should be 8445. If you also enter the public ip of the bot make sure it's resolved by domain and then also should first point to the traefik server. Also make sure the bot is running and did not fail during startup for example because of certificate loading.

**Comment by jbrmg** [comment]
We have set the port configuration to the correct ports. We have also validated that the configuration is in fact used by the bot. Extract from the pod's environment variables:

```
    - name: AzureSettings__InstancePublicPort
      value: "31672"
    - name: AzureSettings__InstanceInternalPort
      value: "8445"
    - name: AzureSettings__CallSignalingPort
      value: "9441"
```

We have also set the `AzureSettings__ServiceDnsName` variable to the domain name as this worked for us locally with ngrok. We did not set the public ip. 

In addition, I can confirm that the bot starts successfully with the final log message after startup being `RecordingBot: running`. No error messages are visible in the startup log (as seen in the first post).

We have made some minor changes to our gateway. Can you please check your logs if the error message has changed on your side? 

Call Id: d41f5e00-a646-461f-a29c-037711187c4b
Timestamp: 2021-06-23T09:27:10Z


Thanks

**Comment by dongkyunn** [comment]
I still see the same failure.
System.TimeoutException: The socket was aborted because an asynchronous receive from the socket did not complete within the allotted timeout of 00:00:04.9530686. The time allotted to this operation may have been a portion of a longer timeout. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request

Since this doesn't use the http protocol, you won't get anything meaningful by running "curl http://localhost:8445". Please make sure Traefik routing uses L4 not L7.

Could you try either Nginx 
or 
running a simple web server on 8445 and see whether you can connect to the server with https? (I know it is not the same, but at least you can rule out the routing problem.)

**Comment by jbrmg** [comment]
We were able to solve the issue. It looks like the issue was traefik having TLS passthrough for the media port configured. We now removed all TLS related configuration for the TCP route from traefik.
